import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() 
{
  const [background, setbackground] = useState('#80808080')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{backgroundColor:background}}>
        <ul className={styles.colorBar}>
          <li onClick={(e)=>(setbackground('red'))} style={{background:'red'}}>Red</li>
          <li onClick={(e)=>(setbackground('yellow'))} style={{background:'yellow'}}>Yellow</li>
          <li onClick={(e)=>(setbackground('pink'))} style={{background:'pink'}}>Pink</li>
        </ul>
      </main>
    </>
  )
}
